<?php
/*
Plugin Name: QPlayer2
Description: 一款简洁小巧的 HTML5 底部悬浮音乐播放器
Author: MoeShin
Version: 2.0.0
Author URI: https://www.moeshin.com/
*/

/*class QPlayer2_Plugin {

    private $options;

    public function __construct()
    {
        $options = get_option('QPlayer2-options');
        $this->options = is_array($options) ? $options : [];
        echo '<pre> $options = ';
        var_dump($options);
        echo '</pre>';
    }

    public function checkbox($id, $title, $description, $default = true)
    {
        add_settings_field($id, $title, function () use ($id, $description, $default) {
            $checked = $this->options[$id];
            echo "<input id=\"<?php echo $id; ?>\" name=\"QPlayer2-options[$id]\" type=\"checkbox\" "
            . checked(isset($checked) ? $checked : $default, true, false)
            . "/><label for=\"$id\">$description</label>";
            }, 'QPlayer2-sections', 'QPlayer2-section');
    }
}

add_action('wp_footer', function () {
    echo 'QPlayer2 footer';
});

add_action('admin_menu', function () {
    add_options_page("QPlayer2", "QPlayer2", 'manage_options', 'QPlayer2',
        function () {
            ?>
            <form action="options.php" method="post">
                <?php
                settings_fields("QPlayer2-options");
                do_settings_sections("QPlayer2-sections");
                submit_button();
                ?>
            </form>
            <?php
        });
});

add_action('admin_init', function () {
    register_setting("QPlayer2-options", "QPlayer2-options");
    add_settings_section("QPlayer2-section", "QPlayer2", function () {}, "QPlayer2-sections");

    $plugin = new QPlayer2_Plugin();
    $plugin->checkbox('cdn', __('CDN'), __('使用 jsDelivr CDN 免费加速 js、css 文件'));
});
*/

/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class QPlayer {
    private $qplayer2_options;

    public function __construct() {
        add_action( 'admin_menu', array( $this, 'qplayer2_add_plugin_page' ) );
        add_action( 'admin_init', array( $this, 'qplayer2_page_init' ) );
    }

    public function qplayer2_add_plugin_page() {
        add_menu_page(
            'QPlayer2', // page_title
            'QPlayer2', // menu_title
            'manage_options', // capability
            'QPlayer2', // menu_slug
            array( $this, 'qplayer2_create_admin_page' ), // function
            'dashicons-admin-generic', // icon_url
            3 // position
        );
    }

    public function qplayer2_create_admin_page() {
        $this->qplayer2_options = get_option( 'qplayer2_option_name' ); ?>

        <div class="wrap">
            <h2>QPlayer2</h2>
            <p></p>
            <?php settings_errors(); ?>

            <form method="post" action="options.php">
                <?php
                settings_fields( 'qplayer2_option_group' );
                do_settings_sections( 'qplayer2-admin' );
                submit_button();
                ?>
            </form>
        </div>
    <?php }

    public function qplayer2_page_init() {
        register_setting(
            'qplayer2_option_group', // option_group
            'qplayer2_option_name', // option_name
            array( $this, 'qplayer2_sanitize' ) // sanitize_callback
        );

        add_settings_section(
            'qplayer2_setting_section', // id
            'Settings', // title
            array( $this, 'qplayer2_section_info' ), // callback
            'qplayer2-admin' // page
        );

        add_settings_field(
            'cdn_0', // id
            'CDN', // title
            array( $this, 'cdn_0_callback' ), // callback
            'qplayer2-admin', // page
            'qplayer2_setting_section' // section
        );

        add_settings_field(
            '_jquery_1', // id
            '加载 jQuery', // title
            array( $this, '_jquery_1_callback' ), // callback
            'qplayer2-admin', // page
            'qplayer2_setting_section' // section
        );

        add_settings_field(
            '_2', // id
            '主题颜色', // title
            array( $this, '_2_callback' ), // callback
            'qplayer2-admin', // page
            'qplayer2_setting_section' // section
        );

        add_settings_field(
            '_3', // id
            '是否旋转封面', // title
            array( $this, '_3_callback' ), // callback
            'qplayer2-admin', // page
            'qplayer2_setting_section' // section
        );

        add_settings_field(
            '_4', // id
            '是否随机播放', // title
            array( $this, '_4_callback' ), // callback
            'qplayer2-admin', // page
            'qplayer2_setting_section' // section
        );

        add_settings_field(
            '_5', // id
            '默认音质', // title
            array( $this, '_5_callback' ), // callback
            'qplayer2-admin', // page
            'qplayer2_setting_section' // section
        );

        add_settings_field(
            '_6', // id
            '歌曲列表', // title
            array( $this, '_6_callback' ), // callback
            'qplayer2-admin', // page
            'qplayer2_setting_section' // section
        );

        add_settings_field(
            '_cookie_7', // id
            '网易云音乐 Cookie', // title
            array( $this, '_cookie_7_callback' ), // callback
            'qplayer2-admin', // page
            'qplayer2_setting_section' // section
        );
    }

    public function qplayer2_sanitize($input) {
        $sanitary_values = array();
        if ( isset( $input['cdn_0'] ) ) {
            $sanitary_values['cdn_0'] = $input['cdn_0'];
        }

        if ( isset( $input['_jquery_1'] ) ) {
            $sanitary_values['_jquery_1'] = $input['_jquery_1'];
        }

        if ( isset( $input['_2'] ) ) {
            $sanitary_values['_2'] = $input['_2'];
        }

        if ( isset( $input['_3'] ) ) {
            $sanitary_values['_3'] = $input['_3'];
        }

        if ( isset( $input['_4'] ) ) {
            $sanitary_values['_4'] = $input['_4'];
        }

        if ( isset( $input['_5'] ) ) {
            $sanitary_values['_5'] = $input['_5'];
        }

        if ( isset( $input['_6'] ) ) {
            $sanitary_values['_6'] = esc_textarea( $input['_6'] );
        }

        if ( isset( $input['_cookie_7'] ) ) {
            $sanitary_values['_cookie_7'] = esc_textarea( $input['_cookie_7'] );
        }

        return  ;
    }

    public function qplayer2_section_info() {

    }

    public function cdn_0_callback() {
        printf(
            '<input type="checkbox" name="qplayer2_option_name[cdn_0]" id="cdn_0" value="cdn_0" %s> <label for="cdn_0">使用 jsDelivr CDN 免费加速 js、css 文件</label>',
            ( isset( $this->qplayer2_options['cdn_0'] ) && $this->qplayer2_options['cdn_0'] === 'cdn_0' ) ? 'checked' : ''
        );
    }

    public function _jquery_1_callback() {
        printf(
            '<input type="checkbox" name="qplayer2_option_name[_jquery_1]" id="_jquery_1" value="_jquery_1" %s> <label for="_jquery_1">若冲突，请关闭</label>',
            ( isset( $this->qplayer2_options['_jquery_1'] ) && $this->qplayer2_options['_jquery_1'] === '_jquery_1' ) ? 'checked' : ''
        );
    }

    public function _2_callback() {
        printf(
            '<input type="checkbox" name="qplayer2_option_name[_2]" id="_2" value="_2" %s> <label for="_2">默认：<span style=\"color: #EE1122\">#EE1122</span></label>',
            ( isset( $this->qplayer2_options['_2'] ) && $this->qplayer2_options['_2'] === '_2' ) ? 'checked' : ''
        );
    }

    public function _3_callback() {
        ?> <fieldset><?php $checked = ( isset( $this->qplayer2_options['_3'] ) && $this->qplayer2_options['_3'] === 'true' ) ? 'checked' : '' ; ?>
            <label for="_3-0"><input type="radio" name="qplayer2_option_name[_3]" id="_3-0" value="true" <?php echo $checked; ?>> 是</label><br>
            <?php $checked = ( isset( $this->qplayer2_options['_3'] ) && $this->qplayer2_options['_3'] === 'false' ) ? 'checked' : '' ; ?>
            <label for="_3-1"><input type="radio" name="qplayer2_option_name[_3]" id="_3-1" value="false" <?php echo $checked; ?>> 否</label></fieldset> <?php
    }

    public function _4_callback() {
        ?> <fieldset><?php $checked = ( isset( $this->qplayer2_options['_4'] ) && $this->qplayer2_options['_4'] === 'true' ) ? 'checked' : '' ; ?>
            <label for="_4-0"><input type="radio" name="qplayer2_option_name[_4]" id="_4-0" value="true" <?php echo $checked; ?>> 是</label><br>
            <?php $checked = ( isset( $this->qplayer2_options['_4'] ) && $this->qplayer2_options['_4'] === 'false' ) ? 'checked' : '' ; ?>
            <label for="_4-1"><input type="radio" name="qplayer2_option_name[_4]" id="_4-1" value="false" <?php echo $checked; ?>> 否</label></fieldset> <?php
    }

    public function _5_callback() {
        ?> <fieldset><?php $checked = ( isset( $this->qplayer2_options['_5'] ) && $this->qplayer2_options['_5'] === '128' ) ? 'checked' : '' ; ?>
            <label for="_5-0"><input type="radio" name="qplayer2_option_name[_5]" id="_5-0" value="128" <?php echo $checked; ?>> 流畅品质 128K</label><br>
            <?php $checked = ( isset( $this->qplayer2_options['_5'] ) && $this->qplayer2_options['_5'] === '192' ) ? 'checked' : '' ; ?>
            <label for="_5-1"><input type="radio" name="qplayer2_option_name[_5]" id="_5-1" value="192" <?php echo $checked; ?>> 清晰品质 192K</label><br>
            <?php $checked = ( isset( $this->qplayer2_options['_5'] ) && $this->qplayer2_options['_5'] === '320' ) ? 'checked' : '' ; ?>
            <label for="_5-2"><input type="radio" name="qplayer2_option_name[_5]" id="_5-2" value="320" <?php echo $checked; ?>> 高品质 320K\'</label></fieldset> <?php
    }

    public function _6_callback() {
        printf(
            '<textarea class="large-text" rows="5" name="qplayer2_option_name[_6]" id="_6">%s</textarea>',
            isset( $this->qplayer2_options['_6'] ) ? esc_attr( $this->qplayer2_options['_6']) : ''
        );
    }

    public function _cookie_7_callback() {
        printf(
            '<textarea class="large-text" rows="5" name="qplayer2_option_name[_cookie_7]" id="_cookie_7">%s</textarea>',
            isset( $this->qplayer2_options['_cookie_7'] ) ? esc_attr( $this->qplayer2_options['_cookie_7']) : ''
        );
    }

}
if ( is_admin() )
    $qplayer2 = new QPlayer();

/*
 * Retrieve this value with:
 * $qplayer2_options = get_option( 'qplayer2_option_name' ); // Array of All Options
 * $cdn_0 = $qplayer2_options['cdn_0']; // CDN
 * $_jquery_1 = $qplayer2_options['_jquery_1']; // 加载 jQuery
 * $_2 = $qplayer2_options['_2']; // 主题颜色
 * $_3 = $qplayer2_options['_3']; // 是否旋转封面
 * $_4 = $qplayer2_options['_4']; // 是否随机播放
 * $_5 = $qplayer2_options['_5']; // 默认音质
 * $_6 = $qplayer2_options['_6']; // 歌曲列表
 * $_cookie_7 = $qplayer2_options['_cookie_7']; // 网易云音乐 Cookie
 */
